package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Login test")
    void generatedTest() {
        step("Open 'https://run.conjoint.ly/hello/tasks'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set username 'mexiy91404@jmpant.com'", () -> {
            step("// todo: just add selenium action");
        });

        step("Set password 'HAyTCkQZWTZW9f'", () -> {
            step("// todo: just add selenium action");
        });

        step("Submit form", () -> {
            step("// todo: just add selenium action");
        });

        step("Verify successful authorization as 'Mexiy'", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://run.conjoint.ly/hello/tasks'", () ->
            open("https://run.conjoint.ly/hello/tasks"));

        step("Page title should have text 'Conjoint.ly'", () -> {
            String expectedTitle = "Conjoint.ly";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://run.conjoint.ly/hello/tasks'", () ->
            open("https://run.conjoint.ly/hello/tasks"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}